
title: My Resume
url: '#'
baseurl: '/'

# Profile information
yourname: Daniel Marczydło
title: 'Full-Stack Web Developer'  ## your title
location: Rzeszów , PL

## Social Profiles
facebook: https://www.facebook.com/daniel.marczydlo
linkedin: https://www.linkedin.com/in/daniel-marczydlo/
github: https://github.com/dmarczydlo


# Update all the sections by editing the files inside _includes folder.
